# Generated by Django 5.2.11 on 2026-02-19 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='favorite_teams',
            field=models.ManyToManyField(blank=True, related_name='fans', to='app.team'),
        ),
    ]
