# Generated by Django 5.2.11 on 2026-02-19 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_team_logo_url_remove_venue_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='sport',
            field=models.CharField(default='Football', max_length=50),
        ),
    ]
