# Generated by Django 5.2.11 on 2026-02-19 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_team_sport'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='league',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
