# Generated by Django 5.2.11 on 2026-02-19 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_match_league'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=500)),
                ('summary', models.TextField(blank=True)),
                ('content', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('source_url', models.URLField(max_length=1000)),
                ('published_at', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(default='Soccer', max_length=100)),
            ],
        ),
    ]
