# Generated by Django 5.2.11 on 2026-02-20 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_newsarticle_published_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='needs_password_change',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('organizer', 'Organizer'), ('user', 'User')], default='user', max_length=20),
        ),
    ]
