# Generated by Django 5.2.11 on 2026-02-20 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_userprofile_needs_password_change_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='view_password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
