# Generated by Django 5.2.11 on 2026-02-20 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_userprofile_view_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='news_articles/'),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='source_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
