# Generated by Django 5.2.11 on 2026-02-20 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_match_exclusive_media_match_highlights_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='department',
            field=models.CharField(blank=True, default='General', max_length=100),
        ),
    ]
