# Generated by Django 5.2.11 on 2026-02-21 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_communitygroup_is_public_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='ticket_price',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=10),
        ),
    ]
