# Generated by Django 5.2.11 on 2026-02-21 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_match_ticket_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='match_events',
            field=models.TextField(blank=True, help_text="List scorers and match events (e.g., Goal: Player Name 23')"),
        ),
    ]
